sudo: false

language: node_js

node_js:
  - "6"

cache:
  directories:
    - node_modules
    - $HOME/.npm
    - $HOME/.cache/yarn

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

  - npm config set spin false
  - npm i -g npm@latest
  - npm i -g angular-cli@latest

install:
  - yarn

script:
  - cd test
  - yarn
  - ng serve
  - yarn run e2e

notifications:
  slack: akveo:q559HckfZMSyZRb803aiLcjH
